server:
  port: 8082
spring:
  application:
    name: customer-service
  sleuth:
    sampler:
      probability: 100
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
